REM
REM                                    ,-
REM                                  ,'::|
REM                                 /::::|
REM                               ,'::::o\
REM            ____........-------,..::?88b                                  ,-' /
REM    _.--    . . . .      .   .  .  .   `-._                           ,-' .;'
REM   <. - :::::o......  ...   . . .. . .  .  .  --._                  ,-'. .;'
REM    `-._  ` `":`:`:`::||||:::::::::::::::::.:. .   --._ ,'|     ,-'.  .;'
REM         _=--       //'doo.. `````:`:`::::::::::.:.:.:. .`-`._-'.   .;'
REM             --..__//juuoooooooooooo. ```:`:`:::::::::.:.:..`'`-'..'
REM                   `-:`oddoooo. ..   ``:`:`:::::::.:.:.:'`-`-'.--'
REM                        `-..oooo  . .  ```:`:::::.:.:.:.`-'.--'
REM LANDSHARK BANDSHARK HANDSHARK MANDELBROT
REM

set landshark=1
REM LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0000
REM LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0001
REM LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0002
REM LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0003
REM LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0004
REM LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0005
REM LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0006
REM LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0007
REM LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0008
REM LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0009
REM LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0010
REM LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0011
REM LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0012
REM LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0013
REM LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0014
REM LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0015
REM LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0016
REM LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0017
REM LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0018
REM LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0019
REM LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0020
REM LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0021
REM LANDSHARK BANDSHARK HANDSHARK MANDELBROT #0022
REM LANDSHARK BANDSHARK HANDS